### ISSUE TITLE
Support for custom namespaces

### ISSUE THREAD

**Issue by soft4good** [woxcab/scrapy_rss#4]
Hello @woxcab, 

Thanks for this package, very cool!

I was wondering, is there a way to produce items with custom namespaces? Like:

```rss
<item>
  ...
  <store:price>$42.42</store:price>
  <store:name>$42.42</store:name>
  ...
</item>
```

And the like? If no, I would be willing to create a PR to support this, can you share some insight on how would you go about implementing such a feature?

Thanks!
Reinier

**Comment by woxcab** [comment]
Hello.
Thanks for the feedback.

This feature will be implemented. Optional namespaces will be specified in the elements and attributes, will be rendered at the root element or at an element that uses specific namespaces — the place choice will be based on the configuration.

**Comment by woxcab** [comment]
Namespaces are implemented.
About feature: https://github.com/woxcab/scrapy_rss#rssitem-derivation-and-namespaces

**Comment by soft4good** [comment]
Thanks @woxcab very cool!
