### ISSUE TITLE
How to export RSS to FTP

### ISSUE THREAD

**Issue by Kvisaz** [woxcab/scrapy_rss#5]
I use  setting with working credentials
FEED_URI = 'ftp://userName:pass@mysite.com/path/to/file.xml'

But scrapy crawl spider make error with message
**ftplib.error_perm: 500 'STOR' not understood**

feedUri is working, i test it in browser
spider is working, i test it locally 

All i want now to export RSS to FTP. How it can be done?

**Comment by woxcab** [comment]
Simple workaround via multiple commands:
set the temporary feed file on local machine like `FEED_FILE = "/tmp/feed.rss"` in the settings.py 
and send this file to the FTP server after Scrapy executing (using [unsafe FTP commands](https://serverfault.com/questions/279176/ftp-uploading-in-bash-script) or SSH `scp "/tmp/feed.rss" userName@mysite.com:/path/to/file.xml` with authorization key usage).
